### ISSUE TITLE
Update requirements 

### ISSUE THREAD

**Issue by omaralsoudanii** [IQSS/dataverse-docker#1]
@4tikhonov @pdurbin 
as mentioned in : https://github.com/IQSS/dataverse/issues/4665

on fresh ubuntu 16.04 installation , The current script on 

> dataverse-docker/dataversedock/step1.sh

 
line 16 : 

> unzip glassfish-4.1.zip 

requires to install unzip by : 

> sudo apt-get install unzip

else the initial.bash will fail silently (doesn't add glassfish dependency and docker compose will fail on step 7 )

Also i noticed the use of wget fails as well on macOS fails since it's not installed on macOS default installation

**Comment by 4tikhonov** [comment]
unzip process moved to running container.
