### ISSUE TITLE
ERROR: authenticationProviders api service Endpoint available from localhost only

### ISSUE THREAD

**Issue by HasanKhatib** [IQSS/dataverse-docker#17]
Trying to invoke the [authenticationProviders](http://localhost:8080/api/admin/authenticationProviders) service causes an error
```{ status:"error", message:"Endpoint available from localhost only. Please contact the dataverse administrator"}```

I tried deploying dataverse image on both 8080 and 8085 ports.

**Comment by pdurbin** [comment]
@HasanKhatib hi! Can you try "ssh'ing" to the Docker container (if you know what I mean) first? Then it should work. You can read more about API blocking at http://guides.dataverse.org/en/4.13/installation/config.html#blockedapipolicy

Hmm. I'm realizing that "Out of the box, all API endpoints are completely open" isn't true though. You must be configured for "localhost-only" which is the default for production installations. (In dev environments it's much more open.)

**Comment by pdurbin** [comment]
@HasanKhatib also, did you say you have a question about ORCID? You can find me at http://chat.dataverse.org

**Comment by HasanKhatib** [comment]
> @HasanKhatib hi! Can you try "ssh'ing" to the Docker container (if you know what I mean) first? Then it should work. You can read more about API blocking at http://guides.dataverse.org/en/4.13/installation/config.html#blockedapipolicy
> 
> Hmm. I'm realizing that "Out of the box, all API endpoints are completely open" isn't true though. You must be configured for "localhost-only" which is the default for production installations. (In dev environments it's much more open.)

I believe this issue happens because for docker containers, my local requests seems to be out of the dockers' localhost scope.
In order to go around this issue I executed `cURL` commands for the api from the docker container image:
```
sudo docker exec -it dataverse /bin/bash

#curl {HTTP_REQUEST_COMMAND}
curl -X POST -H 'Content-type: application/json' --upload-file orcid.json http://localhost:8080/api/admin/authenticationProviders

**Comment by HasanKhatib** [comment]
Another solution I used is to stop the `localhost-only` blocker key in ApiBlockingFilter.java

**Comment by pdurbin** [comment]
@HasanKhatib good job figuring it out. Please be careful with API blocking once you go into production. I noticed some messages from you at http://irclog.iq.harvard.edu/dataverse/2019-05-11 but I should warn you that #dataverse is pretty quiet on weekends. The most active days are Monday through Friday starting around 10 or 11 UTC.

**Comment by poikilotherm** [comment]
My 2 cents: for another, permanent solution, you might take a look at [my approach with unblock-key](https://github.com/IQSS/dataverse-kubernetes/blob/7e7782652c0538cf514ead5c2af19b37cb03be3b/docker/dataverse-k8s/bin/bootstrap-job.sh#L50), as this is always a problem in a K8s environment.
