### ISSUE TITLE
Publishing dataset

### ISSUE THREAD

**Issue by omaralsoudanii** [IQSS/dataverse-docker#2]
On fresh installation using the default DOI settings this error appears when trying to publish : 

>  Error – This dataset may not be published because the EZID Service is currently inaccessible. Please try again. Does the issue continue to persist? If you believe this is an error, please contact Root Support for assistance.

a demo dataset doi : 

> doi:10.5072/FK2/J8FOEQ

**Comment by omaralsoudanii** [comment]
Glassfish logs : 

> 
> [2018-06-19T08:17:36.347+0000] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dvn.core.index.DOIEZIdServiceBean] [tid: _ThreadID=29 _ThreadName=http-listener-1(4)] [timeMillis: 1529396256347] [levelValue: 900] [[
>   cause]]
> 
> [2018-06-19T08:17:36.347+0000] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dvn.core.index.DOIEZIdServiceBean] [tid: _ThreadID=29 _ThreadName=http-listener-1(4)] [timeMillis: 1529396256347] [levelValue: 900] [[
>   message bad request - _target: enter a valid URL]]
> 
> [2018-06-19T08:17:36.351+0000] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.DatasetPage] [tid: _ThreadID=29 _ThreadName=http-listener-1(4)] [timeMillis: 1529396256351] [levelValue: 1000] [[
>   This dataset may not be published because the <a href=https://ezid.cdlib.org target="_blank"/> EZID </a> Service  is currently inaccessible. Please try again. Does the issue continue to persist?]]
> 
>

**Comment by omaralsoudanii** [comment]
@4tikhonov thank you for looking into this , 
What do you mean by valid URL of dataset landing page and is it something i change from my side ?

**Comment by omaralsoudanii** [comment]
@4tikhonov i found the problem , This needs to be added glassfish to the JVM options 

> Ddataverse.siteUrl

For demo purpose this needs to be added to docker steps : 

> asadmin create-jvm-options '-Ddataverse.siteUrl=http\://demo.dataverse.org'

**Comment by pdurbin** [comment]
@omaralsoudanii good catch. It reminds me of the line about dataverse.siteUrl in conf/docker-aio/readme.txt that @pameyer added: https://github.com/IQSS/dataverse/blob/v4.9/conf/docker-aio/readme.txt#L22

**Comment by 4tikhonov** [comment]
Thanks @omaralsoudanii, we'll update Docker image then. 

And I don't know if you're interested, but we just published Kubernetes specification for Google Cloud: https://github.com/IQSS/dataverse-docker/tree/master/kubernetes

**Comment by 4tikhonov** [comment]
I've added this command to Dataverse setup process in Docker, should work now:
 /usr/local/glassfish4/glassfish/bin/asadmin create-jvm-options "\-Ddataverse.siteUrl=http\:\/\/demo.dataverse.org"
