### ISSUE TITLE
getting error when I'm trying to publish dataset.

### ISSUE THREAD

**Issue by benzaked** [IQSS/dataverse-docker#30]
I get this message when I trying to publish dataset.
"This dataset may not be published due to an error when contacting the DataCite Service. Please try again. If you believe this is an error, please **contact**..."
I sow [this](https://github.com/IQSS/dataverse-docker/issues/2) issue so I tried this : 
`./asadmin create-jvm-options "-Ddataverse.siteUrl=http\://my server IP\:8085"
`after exec to the dataverse container. the command went successfully but still getting the same error. (tried to restart the containers.) also, I tried 
`asadmin create-jvm-options "-Ddataverse.siteUrl=http\://localhost\:8085"` . no change

please help! Thank you!

**Comment by 4tikhonov** [comment]
Is it test server or you need real DOIs? If it's first, you can use FAKE to avoid this kind of problems: 
curl -X PUT -d DataCite http://localhost:8080/api/admin/settings/:DoiProvider

More here: http://guides.dataverse.org/en/latest/installation/config.html#id139

**Comment by benzaked** [comment]
I need the server to store datasets for my very small organization. the ports will be opened only to the internal network. what should I do? 
Thanks!!

**Comment by 4tikhonov** [comment]
Ok, if you don't need a persistent DOI the solution with FAKE should work.

**Comment by benzaked** [comment]
How do I create it ?

בתאריך יום ד׳, 20 בנוב׳ 2019, 12:04, מאת Vyacheslav Tykhonov ‏<
notifications@github.com>:

**Comment by benzaked** [comment]
I make fake DOls by 
curl -X PUT -d DataCite http://localhost:8080/api/admin/settings/:DoiProvider
and get "{"status":"OK","data":{":DoiProvider":"DataCite"}}"
but it didn't solve the problem.

**Comment by benzaked** [comment]
Thank you! 
curl -X PUT -d FAKE http://localhost:8080/api/admin/settings/:DoiProvider 
solve it.

**Comment by benzaked** [comment]
@4tikhonov  I have a silly question. do you know how to delete the DOI link? 
It's leading to 404 page so I wish to delete it. 
Thanks!

**Comment by 4tikhonov** [comment]
Do you mean to delete a landing page after the persistent DOI, right?

**Comment by benzaked** [comment]
I want to delete this link from the title of the dataset after publishing it. 
![image](https://user-images.githubusercontent.com/53477112/69724252-342bc500-1124-11ea-9f50-1fd27ac64e58.png)

**Comment by 4tikhonov** [comment]
I think it's part of the citation block, it's not possible in the default setup.

**Comment by benzaked** [comment]
@4tikhonov  after inspecting the page. it is part of the CitationBlock. it is not possible to delete the variable from the code after the installation?
Thank you very much for all the help and the quick replay.

**Comment by pdurbin** [comment]
@benzaked we consider it a feature that people can click the DOI URL (or easily right click to copy the URL) so the dataset can be easily shared via DOI. I'm confused why you would want to disable this. 😄 

Also, isn't this a bit off topic for the original issue here? 😄

**Comment by benzaked** [comment]
@pdurbin  most of our datasets are private(users privacy reasons) and the server open only to the organization network.

**Comment by pdurbin** [comment]
@benzaked ok, thanks. We hear this from time to time. Most users of Dataverse want at least all the metadata about their published datasets to be public and searchable by Google etc. However, increasingly some installations are interested in running Dataverse behind their corporate firewall and have zero interest is putting their installation of Dataverse on the public internet. They don't want their installation to be crawled by Google. They don't want metadata to be pushed to DataCite when they publish their datasets. If any of this describes your situation, please consider creating an issue at https://github.com/IQSS/dataverse/issues with as many details as possible describing your use case. You aren't alone but what you're describing is not currently well supported and perhaps a fresh issue will spur some discussion.
