### ISSUE TITLE
automatic logout

### ISSUE THREAD

**Issue by benzaked** [IQSS/dataverse-docker#31]
the system forwards to the new page unlogin after clicking on some button. for example:
login > add data.throw the user to the login page.
or after login and entering to some datasets. need to log in again.
Does anyone know why?
Thanks!

I also opened an issue [here](https://github.com/IQSS/dataverse/issues/6384) 
no answer so far.

**Comment by benzaked** [comment]
anyone?

**Comment by 4tikhonov** [comment]
I've re-installed everything from the scratch but Dataverse seems to be working fine.

**Comment by pdurbin** [comment]
> I also opened an issue [here](https://github.com/IQSS/dataverse/issues/6384)
> no answer so far.

@benzaked well, about 20 minutes after you opened that issue I replied with this: https://github.com/IQSS/dataverse/issues/6384#issuecomment-555976065

It may not have been the best reply I've ever written but does it count for something? 😄

**Comment by benzaked** [comment]
Ok, After deleting the docker-images from the server and re-install it, the problem solved. Thank you all!
