### ISSUE TITLE
Cannot connect to S3-Compatible object storage

### ISSUE THREAD

**Issue by gammaeva** [IQSS/dataverse-docker#54]
Hi all !

I'm unable to connect to my swift object storage (S3 compatible). I'm having this error :

` om.amazonaws.AmazonClientException: Cannot instantiate a S3 client; check your AWS credentials and region`

I'm confused because I can call the s3 swift api with awscli, so my config et credentials files are good.

This is my configuration:

```
        dataverse.files.s3.profile=default
        dataverse.files.storage-driver-id=s3
        dataverse.files.s3.type=s3
        dataverse.files.s3.bucket-name=datachallenge2020
        dataverse.files.s3.custom-endpoint-region=gra
        dataverse.files.s3.path-style-access=true
        dataverse.files.s3.custom-endpoint-url=https://s3.gra.cloud.ovh.net
        dataverse.files.s3.label=s3
        dataverse.files.s3.payload-signing=true
```

config file:

```
[default]
region = gra

```
credentials file:

```
[default]
aws_access_key_id = *******************************
aws_secret_access_key = *****************************
```

I put these configuration files in the home directory of the user "payara". I think this user runs the glassfish server:

Any suggestions?

Maeva

**Comment by pdurbin** [comment]
@gammaeva hi! I'm sorry no one ever got back to you. Did you ever figure it out?

**Comment by gammaeva** [comment]
hi I gave up and I used the swift configuration instead of the s3 configuration and it works now :)

**Comment by 4tikhonov** [comment]
HI @gammaeva, sorry for the late reply, we are using S3 for the different Dataverse instances installed from the Docker version, however it's mounted as a network volume on /data folder. Please check here for more details:
https://www.nakivo.com/blog/mount-amazon-s3-as-a-drive-how-to-guide/
