### ISSUE TITLE
Question about updating Dataverse

### ISSUE THREAD

**Issue by schorcht-ioer** [IQSS/dataverse-docker#83]
Dear Devs,

today we tested updating Dataverse from v.5.10 to 5.11.1, which worked without any problems. All datasets, accounts and customizations (e.g. CustomLogo) have been preserved, which is very good :)

However, we noticed that older versions, such as 5.2, could not be easily updated to 5.11.1, because the structure of the yml-file had changed a lot. We had adjusted the war-files and the versions, but dataverse could not be started afterwards (after the update 5.2 --> 5.11.1). 

Therefore we would like to know if future versions can also be updated as easily as the last ones? At least we would appreciate if you could provide update instructions in case of fundamental changes.

Thanks a lot, martin

**Comment by 4tikhonov** [comment]
HI @schorcht-ioer, versions before 5.3 were running on old version of Payara, it's upgraded now.

**Comment by schorcht-ioer** [comment]
we have tested again updating from 5.2 to 5.11.1 and now it works (:
(we had set a wrong value at POSTGRES_DB)
