### ISSUE TITLE
Getting duplicates of External Tools after docker down/up

### ISSUE THREAD

**Issue by schorcht-ioer** [IQSS/dataverse-docker#88]
Dear Devs,

After restarting Docker with down/up (e.g. to test updates) we get duplicates for external tool previewer.

![grafik](https://github.com/IQSS/dataverse-docker/assets/123582538/1dd6a692-2823-46d4-800a-2d088b8413af)

Probably this is because the file "07-previewers.sh" in the "init.d" folder is executed again at every reboot.

Is there a way/command to delete all external tools?

thx, martin

**Comment by 4tikhonov** [comment]
I think it was fixed in DataverseNO, we just need to merge it: https://github.com/DataverseNO/dataverse-docker/tree/dataverse.no/distros/dataverse.no/init.d
