### ISSUE TITLE
Dataverse-Docker V6.2

### ISSUE THREAD

**Issue by DominikWA** [IQSS/dataverse-docker#97]
Hi Dataverse Team,

I am an admin of a Dataverse instance and have been eagerly following the development of the project. I was wondering if you could provide an update on when the latest Dataverse version, 6.2, is expected to be released in docker? Additionally, is there a roadmap available that would outlines the upcoming docker releases?

Thank you for all your hard work and dedication to this project. I appreciate any information you can provide.

Best regards,
Dominik

**Comment by pdurbin** [comment]
@DominikWA hi! If it helps, a 6.2 image is already available from upstream. It's the "alpha" image at https://hub.docker.com/r/gdcc/dataverse

If you'd like to try it, I recommend the "demo" tutorial at https://guides.dataverse.org/en/6.2/container/running/demo.html

We'd like to tag these images some day. It's the first item on our list having to do with making these images more production ready:

- https://github.com/IQSS/dataverse/pull/10585
